### PR TITLE
Add shallow clone option

### PR DESCRIPTION
**Pull request by paulbovbel**
This adds the ability to do a shallow clone of a specified repository branch

### CODE REVIEW

**Comment by paulbovbel** [comment]
Test failures look unrelated, but please verify.

**Comment by paulbovbel** [comment]
--shallow checkout with version: git_sha should work on certain git hosts but not on github (https://stackoverflow.com/a/43136160).

**Comment by dirk-thomas** [comment]
@paulbovbel Friendly ping.

**Comment by dirk-thomas** [comment]
@paulbovbel Another ping.

**Comment by paulbovbel** [comment]
Hi @dirk-thomas, I've taken a look through the tests and it looks like it'll be a bit complicated to add tests for the `import` modifiers (`--recursive`, and now `--shallow`). I'll try to swing back around to this soon. Would you like me to close the PR in the meantime?

**Comment by dirk-thomas** [comment]
No, the PR can stay around as long as necessary. Since your PR only adds the shallow option the test can focus on that case. The recursive option (already merged) can been covered separately.

I just think having test coverage if very important since it ensures that the feature keeps working (since I don't have enough time to rigorously check each and every case after a change).

**Comment by dirk-thomas** [comment]
> I'll try to swing back around to this soon.

@paulbovbel Friendly ping checking if you had some time for this.

**Comment by dirk-thomas** [comment]
@paulbovbel Any chance you can revisit the missing tests for this feature?

**Comment by dirk-thomas** [comment]
@paulbovbel Are you still interested in getting this enhancement merged?

**Comment by paulbovbel** [comment]
Hi @dirk-thomas, I'll close this PR for now, thanks.

**Pull request closed without merging**
