### PR TITLE
Add --exact-with-tags option to export command.

### PR DESCRIPTION
**Pull request by crdelsey**
This addresses #109.

This adds a new command line option to the `export` sub-command: `--exact-with-tags`.

`--exact-with-tags` does what `--exact` does currently. That is, it reports the exact hash ID of the current commit or replaces it with a tag name if one can be found.

`--exact` now only reports the exact hash ID and does not replace with a tag.

`--exact` is a bit friendlier to automation, while `--exact-with-tags` is a bit friendlier to humans

Note that the "with-tags" part is ignored by all version control tools except Git.

### CODE REVIEW

**Comment by crdelsey** [comment]
I want to do a bit of refactoring on the export method still. That's why this is a draft PR.

**Comment by dirk-thomas** [comment]
I [rephrased the help messages](https://github.com/dirk-thomas/vcstool/pull/115/commits/6b96eca770c5e6ce88db1df9a8b6029bb39b973a) a bit and [de-duplicated the return logic](https://github.com/dirk-thomas/vcstool/pull/115/commits/5e9944a002bc92a9c5851fdb06db9e3c291b102f). I hope that makes sense to you.

While my changes also address some linter failures the tests checking the `export` command still fail. Please update them to pass again as well as extend them to cover the new option.

> I want to do a bit of refactoring on the export method still.

Please keep any independent refactoring in a separate PR so this has an as minimal as possible diff.

**Comment by crdelsey** [comment]
> Please keep any independent refactoring in a separate PR so this has an as minimal as possible diff.

Ok. I'll defer the refactoring. You took care of the thing that was bothering me most anyhow; the duplication of the return logic. Thanks for that, by the way.

The CI failure seems unrelated to this change, so I'm going to go ahead and mark this PR ready.

**Comment by dirk-thomas** [comment]
> The CI failure seems unrelated to this change, so I'm going to go ahead and mark this PR ready.

I addressed the CI failure in #117. Please rebase your branch on top of the latest state of the master branch to pass CI.

**Comment by crdelsey** [comment]
Thanks. That did it and it is passing CI now.

**Comment by dirk-thomas** [comment]
@crdelsey Thanks for the contribution.

@murrdpirate FYI since you requested tags being used in the exact export and after this you will need to use the new option `--exact-with-tags`.

**Comment by murrdpirate** [comment]
Thanks for the heads up!

**Comment by JanosToth1989** [comment]
Hi,
I'm using the tool to create release from more repositories on github. I tag my current version and run the exact-with tags but always get the commit hash like exact. How can I get tags in the yaml file? 
I installed vcs via ROS2 Humble.

**Pull request merged**
