### PR TITLE
Clarify vcstools ambiguity

### PR DESCRIPTION
**Pull request by davetcoleman**
https://github.com/vcstools/vcstools/issues/135

### CODE REVIEW

**Comment by dirk-thomas** [comment]
This tool has nothing to do with ROS 2 - not even with ROS. It simply operates on working copies of various vcs types in the file system. Therefore I don't think this patch makes sense.

**Comment by dirk-thomas** [comment]
I assume my answer clarified why the current patch can't be merged as-is. Since there was no further response I assume this can be closed.

Please feel free to comment and the ticket can be reopened if necessary.

**Comment by dirk-thomas** [comment]
> This is very frustrating. OSRF has two projects with basically the exact same name but you won't help users understand which one to use.

Just to clarify: `vcstool` (this repo) is not an OSRF project.

> I asks for help and nothing comes out of that. So I create two PRs to help document the mess and you close this one.

After you opened this ticket I commented on it that the currently proposed patch doesn't make much sense since this project is not related to ROS 2. After no further response the ticket was closed because of inactivity.

If you would like to iterate on the description and update this patch I am more than happy to reopen and merge this.

**Comment by davetcoleman** [comment]
After the first line of the README can you please add a clarification:

"vcstool should not be confused with [vcstools](https://github.com/vcstools/vcstools) which similarly aides in using multiple repositories but is different because [I'm still not sure, please insert]"

**Comment by dirk-thomas** [comment]
See #68 which adds a note to the readme.

**Comment by davetcoleman** [comment]
Awesome, thanks!

I'm starting to use vcs more... previously I had written my own bash scripts to iterate through repos but im realizing this tool can do it for me :)

**Pull request closed without merging**
