### PR TITLE
improve output of export command in case of errors

### PR DESCRIPTION
**Pull request by dirk-thomas**
Further improve #11.

### CODE REVIEW

**Comment by NikolausDemmel** [comment]
Cool. Thanks for the quick response.

Example output:

```
$ vcs export
repositories:
  Framework:
    type: git
    error: "Could not determine ref: fatal: No upstream configured for branch 'foo'"

Framework: Could not determine ref: fatal: No upstream configured for branch 'foo'
```

Did you intend for the error to be printed twice?

In any case. For me this is more than good enough. Cheers!

**Comment by dirk-thomas** [comment]
I was still shuffling around code on this PR - now it should be final and only print errors once.

**Comment by NikolausDemmel** [comment]
+1

Looks good:
```
$ vcs export
repositories:
Framework: Could not determine ref: fatal: No upstream configured for branch 'foo'
```
Thanks for implementing!

**Comment by dirk-thomas** [comment]
Thanks for testing!

**Pull request merged**
